### ISSUE TITLE
Jenkins install of chapter 7 does not create initial password as reported

### ISSUE THREAD

**Issue by hholcomb** [PacktPublishing/-Learn-Helm#10]
When the install of the jenkins application is performed as specified in Chapter 7 of Learn Helm book, the output indicates that the initial password for the admin user is found in /var/jenkins_home/secrets/initialAdminPassword
and indicates how to see the contents of that file.

However, there is no such file under /var/jenkins_home/secrets
I don't see anything in the book that indicates you expected to be creating a Jenkins Admin account.

Did you specify creation of an admin account or is the password in some other location?

**Comment by deweya** [comment]
I disabled this to avoid users from needing to authenticate while following along with the example. The message will still appear in the notes, but the secret will not be created.
