### ISSUE TITLE
operator-sdk new option not available in versions 1.x

### ISSUE THREAD

**Issue by hholcomb** [PacktPublishing/-Learn-Helm#11]
I installed the latest version of operator-sdk (v1.3.0) for performing the tasks from chapter 8 of Learn Helm and discovered a issue

The "oerator-sdk new" command specified in the "Scaffolding the operator file structure" section of Chapter 8 is no longer available in the operator-sdk application starting with versions 1.0.

It would appear that one should now be creating a helm operator as per
https://sdk.operatorframework.io/docs/building-operators/helm/tutorial/

Do you have an update for the  chapter 8 procedure when using the newer version of the operator-sdk application?

**Comment by deweya** [comment]
If you want to use the latest operator-sdk, the equivalent "new" command would be -
```
operator-sdk init --plugins helm --kind Guestbook --helm-chart Learn-Helm/helm-charts/charts/nginx/
```

The equivalent "build" command would be -
```
export USERNAME=<quay-namespace>
make docker-build docker-push IMG=quay.io/$USERNAME/guestbook-operator
```

And to deploy you can use - 
```
make deploy IMG=quay.io/$USERNAME/guestbook-operator
```
