### ISSUE TITLE
Missing charts/guestbook/redis

### ISSUE THREAD

**Issue by gvanriper** [PacktPublishing/-Learn-Helm#6]
Error on helm template my-guestbook Learn-Helm/helm-charts/charts/guestbook since there is no redis chart in repo.

**Comment by gvanriper** [comment]
It appears to be caused by the .gitignore in the guestbook directory.

**Comment by deweya** [comment]
`charts/` dirs are typically included in a .gitignore if using dependency management (`dependencies` section of Chart.yaml). To download the Redis chart, you can run:

```
helm dependency update Learn-Helm/helm-charts/charts/guestbook
```

Afterwards, the deployment should work

**Comment by gvanriper** [comment]
I figured it out. Sorry, I should have just closed. I was working fresh from Chapter 6 and had to go back to recreating.
