### ISSUE TITLE
chart_schema.yaml file missing entries

### ISSUE THREAD

**Issue by hholcomb** [PacktPublishing/-Learn-Helm#7]
When I attempt to use the ct application to validate the Guestbook files as documented in the chart testing tools section of chapter 6 in the Learn Helm book, there are errors generated indicating that entries are missing from the the version of the chart_schema.yaml file in your github tree at -Learn-Helm.

I was able to bring in the version of that file from the ct application tree to my clone of that github tree and then could get thru the lint analysis of the guestbook and nginx applications.

It seems this file needs to be updated

**Comment by deweya** [comment]
I ran `ct lint` at the root level of this repo (after making a change to one of the charts), and it ran as expected. What's the exact error you're getting?

Successful output from my test below for comparison
```
adewey:  ~/Learn-Helm  |master U:1 ✗|
→ ct lint
Linting charts...
Using config file:  /home/adewey/Learn-Helm/ct.yaml
------------------------------------------------------------------------------------------------------------------------
 Configuration
------------------------------------------------------------------------------------------------------------------------
Remote: origin
TargetBranch: master
BuildId: 
LintConf: /home/adewey/.ct/lintconf.yaml
ChartYamlSchema: chart_schema.yaml
ValidateMaintainers: false
ValidateChartSchema: true
ValidateYaml: true
CheckVersionIncrement: true
ProcessAllCharts: false
Charts: []
ChartRepos: [bitnami=https://charts.bitnami.com/bitnami]
ChartDirs: [helm-charts/charts]
ExcludedCharts: []
HelmExtraArgs: 
HelmRepoExtraArgs: []
Debug: false
Upgrade: false
SkipMissingValues: false
Namespace: 
ReleaseLabel: 
------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------------------------------------------------------------------
 Charts to be processed:
------------------------------------------------------------------------------------------------------------------------
 nginx => (version: "1.0.1", path: "helm-charts/charts/nginx")
------------------------------------------------------------------------------------------------------------------------

"bitnami" already exists with the same configuration, skipping
Linting chart 'nginx => (version: "1.0.1", path: "helm-charts/charts/nginx")'
Checking chart 'nginx => (version: "1.0.1", path: "helm-charts/charts/nginx")' for a version bump...
Old chart version: 1.0.0
New chart version: 1.0.1
Chart version ok.
Validating /home/adewey/Learn-Helm/helm-charts/charts/nginx/Chart.yaml...
Validation success! 👍

Linting chart with values file 'helm-charts/charts/nginx/ci/clusterip-values.yaml'...

==> Linting helm-charts/charts/nginx
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, 0 chart(s) failed

Linting chart with values file 'helm-charts/charts/nginx/ci/nodeport-values.yaml'...

==> Linting helm-charts/charts/nginx
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, 0 chart(s) failed
------------------------------------------------------------------------------------------------------------------------
 ✔︎ nginx => (version: "1.0.1", path: "helm-charts/charts/nginx")
------------------------------------------------------------------------------------------------------------------------
All charts linted successfully
```

**Comment by hholcomb** [comment]
Austin


When following the steps in chapter 6 and performing the ct lint-and-install cmd on the repo from the branch containing the updated Chart files, I get the error shown below
11111111111111111111111111111111111111111111111111
[centos@ip-10-193-1-13 -Learn-Helm]$ /home/centos/helm/helm_chart_testing/ct/ct lint-and-install
Linting and installing charts...
------------------------------------------------------------------------------------------------------------------------ 
Charts to be processed:
------------------------------------------------------------------------------------------------------------------------ 
guestbook => (version: "1.0.1", path: "helm-charts/charts/guestbook") 
nginx => (version: "1.0.1", path: "helm-charts/charts/nginx")
------------------------------------------------------------------------------------------------------------------------
"bitnami" already exists with the same configuration, skipping
Hang tight while we grab the latest from your chart repositories......
Successfully got an update from the "hh-first-repo" chart repository...
Successfully got an update from the "prometheus-community" chart repository...
Successfully got an update from the "bitnami" chart repository...
Successfully got an update from the "stable" chart repository
Update Complete.  ?Happy Helming!?
Saving 1 charts
Downloading redis from repo https://charts.bitnami.com/bitnami
Deleting outdated charts
Linting chart 'guestbook => (version: "1.0.1", path: "helm-charts/charts/guestbook")'
Checking chart 'guestbook => (version: "1.0.1", path: "helm-charts/charts/guestbook")' for a version bump...
Old chart version: 1.0.0
New chart version: 1.0.1
Chart version ok.
Validating /home/centos/helm/Learning_Helm_github_repo/-Learn-Helm/helm-charts/charts/guestbook/Chart.yaml...
Validation failed!
Error validating data '/home/centos/helm/Learning_Helm_github_repo/-Learn-Helm/helm-charts/charts/guestbook/Chart.yaml' with schema '/home/centos/helm/Learning_Helm_github_repo/-Learn-Helm/chart_schema.yaml'        
apiVersion: Unexpected element        
type: Unexpected element        
dependencies: Unexpected element
1111111111111111111111111111111111111111111111111111111111111111111111111111111111111

Note - The above is only the beginning part of the output.  
There is also an error for the nginx Chart.yaml file
When I updated the schema file in the repo to match what is provided with the ct application (which does include a specification for apiVersion) I no longer had validation errors.

when I run the cmd 
$ ct lint 
on the updated repo tree,I also get the unexpected element error

Separate issue
I am attempting to following your process for using the --upgrade option on the ct lint-and-install command and receive the following error
git 'worktree' is not a git command 
when executing the cmd
$ /home/centos/helm/helm_chart_testing/ct/ct lint-and-install --upgrade
Any thoughts on what I may be doing wrong?  
There does not seem to be much documentation on ct.  I will start going thru the ct source code to understand what it is trying to do when it gets to this error condition.

Howard Holcombe-----Original Message-----

**Comment by deweya** [comment]
What version of `ct` are you using? There may be a version discrepancy causing us to get different results. My version is:
```
Version:	 v3.0.0-rc.1
Git commit:	 16513fad69626142ccd84e9171397df317806cb0
Date:		 2020-04-03T03:54:12Z
License:	 Apache 2.0
```

Regarding your git issue, ct requires git version 2.17.0 or later. Your version of git probably does not include the `git worktree` command.

**Comment by hholcomb** [comment]
I am running ct version 3.3.1 
Date 2020-11-30T20:10:04Z

The ct config files in the newer version seem to be at a different location that in your version.
Newer looks for them in current directory, in ~/.ct and then in /etc/ct according to help for the ct command and the README file
this location matches what is in the Learn Helm book

your output shows
Using config file:  /home/adewey/Learn-Helm/ct.yaml


I am using git version 1.8.3.1 - so that is a problem as the book's section on installing the Chart Testing tools indicates version 2.17.0 or higher is required

**Comment by deweya** [comment]
I tried with the new version, and it was still successful. 

I'd like to be able to reproduce the error. What contents do you have inside `/home/centos/helm/helm_chart_testing/ct/`? What's the diff between master branch and your local clone? To confirm, are you running ct at the root of this repo?

**Comment by hholcomb** [comment]
To answer your questions
1. the contents of the /home/centos/helm/helm_chart_testing/ct/ subdir on my instance is as follows
         a. the ct executable, 
          b. the LICENSE file
          c. the README.md file
          d. the etc  subdir  which contains the chart_schema.yaml and the 
                    lintconf.yaml files 
                    
                    note this subdir was populated with the expanded files from the chart-testing_3.3.1_linux_amd64.tar.gz tarball

2. the file differences between the master branch and my chart-testing-example branch (as identified by the cmd
$ git diff chart-testing-example master
 are
      a. chart_schema.yaml    - in the  chart-testing-example branch replaced the default file with the one from the ct application
      b. helm-charts/charts/guestbook/Chart.yaml - in the chart-testing-example branch modified the description and version 
                   entries as per book
      c. helm-charts/charts/nginx/Chart.yaml - in the chart-testing-example branch modified the description and version entries
                   as per book

3. I believe that I am running the ct command from the root of the repo  (at /home/centos/helm/Learning_Helm_github_repo/-Learn-Helm)  as the .git and .gitignore files are there.

**Comment by deweya** [comment]
What versions of yamale and yamllint are you using? You can use `pip freeze` to help with this. The versions I'm using are:
```
yamale==2.0.1
yamllint==1.20.0
```

If the underlying yamale versions are different, this could explain why you're seeing schema validation issues. Yamllint probably doesn't have an affect, but won't hurt to shoot it over since it's also a requirement for ct

**Comment by hholcomb** [comment]
I am using 
yamale version 3.0.4
python version 3.6.8
yamllint v 1.25.0

on CentOS 7.9 Linux

**Comment by hholcomb** [comment]
when I specify --debug as a part of the ct lint-and-install command I see that the problem happens when executing the cmds
$ yamale --schema chart_schema.yaml helm-charts/charts/guestbook/Charts.yaml
$ yamale --schema chart_schema.yaml helm-charts/charts/nginx/Charts.yaml

The output associated with the problem is
apiVersion: Unexpected element
This happens when the chart_schema.yaml file at the top of the git repo is the version from the master branch

When I specifically tell ct to use the chart_schema.yaml file from the ct tree by executing the following cmd
$ /home/centos/helm/helm_chart_testing/ct/ct lint-and-install --chart-yaml-schema ../../helm_chart_testing/ct/etc /chart_schema.yaml --debug

from the subdir /home/centos/helm/Learning_Helm_github.repo/-Learn-Helm
then the yamale application is able to successfully validate the revised helm-charts/charts/guestbook/Chart.yaml file
and there is no error regarding the apiVersion

Thus it may be that your version of ct is not using the version of chart_schema.yaml from the current location but rather the version from ~/.ct

Austin, when you run the ct command with the --debug option in your environment where does the output show as the location for the chart_schema.yaml file in the yamale command ?

note - the output showing the configuration file information is generated, in the newer version of ct, only when the --print-config option is specified

**Comment by hholcomb** [comment]
in the section titled Installing the chart testing tools of chapter 6 you indicate 
When installing yamale via pip you specify using the --user option so that the application is installed in the user's area

When installing yamale from the archive you specify that one should use the command
$ python setup.py install
which may require root access

Why don't you specify the install command for the archive version to be
$ python setup.py install  --user
which will install the application in the user's area rather than the system area ?

**Comment by hholcomb** [comment]
After installing a newer version of git, I was able use the command
$ /home/centos/helm/helm_chart_testing/ct/ct lint-and-install --chart-yaml-schema ../../helm_chart_testing/ct/etc /chart_schema.yaml --debug --upgrade

to successfully perform the chart testing including the upgrades

**Comment by deweya** [comment]
@hholcomb I updated my yamale installation to v3.0.4 and see the schema error you're referring to. I'll update the chart_schema file accordingly. Thanks for pointing this out.

In response to your yamale installation question, I was following the instructions on the [yamale installation page](https://github.com/23andMe/Yamale#install)

**Comment by deweya** [comment]
Chart schema has been updated - https://github.com/PacktPublishing/-Learn-Helm/blob/master/chart_schema.yaml

**Comment by hholcomb** [comment]
thanks for helping me to resolve this issue
