### ISSUE TITLE
github replacing master branch by main branch causes problems for jenkins job

### ISSUE THREAD

**Issue by hholcomb** [PacktPublishing/-Learn-Helm#9]
As per https://github.com/github/renaming
github is changing their repos so that the default branch is main rather than master.

When I created, as per chapter 5 of Learn-Helm, the github repo for the helm chart repository on 3 Feb 2021, I ended up with a main branch rather than a master branch as the default branch in the repo.

The first time that the Test and Release Helm Charts Jenkins job of Chapter 7 runs, it attempts to push the new chart artifacts into the master branch of the chart repository and that action fails as there is no such branch.

I was able to work around the issue by renaming the main branch in the github repo back to master, creating a clone of this revised repo and then running the jenkins job.  Now the jenkins job successfully completes.

Can the jenkins job be made to utilize either master or main as appropriate?

**Comment by deweya** [comment]
I updated the job to push to `main` by default to accommodate the new default branch name. 

If readers need to push to `master`, they can set the `githubPagesBaseBranch` value by following this example:
```
helm install jenkins codecentric/jenkins \
-n chapter7 --version 1.5.1 \
--set githubUsername=$USERNAME \
--set githubPassword=$PASSWORD \
--set githubForkUrl=https://github.com/$USERNAME/-Learn-Helm.git \
--set githubPagesRepoUrl=https://github.com/$USERNAME/Learn-Helm-Chart-Repository.git \
--set githubPagesBaseBranch=master \
--values Learn-Helm/jenkins/values.yaml
```
